### PR TITLE
Make the length of the padding adjustable (and constant)

### PR DESCRIPTION
**Pull request by petervdn**
Btw, i found the padding of 1 sec (minimal) way too long, so i added it as a param to the method. Also, you seem want to have every sample start on rounded seconds, but since the timings are defined in the json, i didnt see the advantage of that (also adds more spacing than necessary).

No i idea if you want this, but it helped me make my resulting file a few minutes shorter.

### CODE REVIEW

**Comment by kribblo** [comment]
It has been slightly useful to align on second boundaries when inspecting the resulting WAV at times, and the silent gaps does not really affect output size after compression; but I am not at all against making it configurable, and the alignment isn't all that important.

Some suggestions: Make the second parameter an `options` object instead, that way any future configurations can go into that instead of adding more parameters:

```javascript
const options = {
    padding: 200,
    someFutureOption: true
};
wavAudioSprite(files, options).then(onResult);
```
Perhaps make it so that default still is aligning on seconds, but if padding is given, it just uses that gap.

**Comment by petervdn** [comment]
Cool, sounds like a plan!

**Comment by kribblo** [comment]
Thanks, merged and published

**Comment by petervdn** [comment]
\o/ My very first PR! :)

**Pull request merged**
